apiVersion: v1
kind: ConfigMap
metadata:
  name: shikra
  labels:
    app: shikra
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shikra?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: "shikra"
  SPRING_DATASOURCE_PASSWORD: "shikra"