server:
  port: 8081
  servlet:
    context-path: /

auth:
  channels:
    basic:
      realm: Shikra

spring:
  jackson:
    serialization:
      indent_output: false
      write_dates_as_timestamps: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

  redis:
    database: 0  # 默认为0
    host: redis
    port: 6379
    password: "" # 默认为空
    timeout: 0  # 连接超时时间（毫秒）
    pool:
      max-active: 3 # 最大连接数，负数不限制
      max-wait: -1 # 最大阻塞等待时间，负值不限制
      max-idle: 1  # 最大空闲连接
      min-idle: 0 # 最小空闲连接

  flyway:
    locations: ["classpath:/db/migration"]

  mail:
    host: smtp.qq.com
    username: xracoon@qq.com
    password: qphdzvckozjldafh
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true

    sender: xracoon@qq.com

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info.enabled: true
    health.enabled: true

info:
  info2222: aaaabbbb